// <auto-generated />
using Infrastructure.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190619121318_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Infrastructure.Models.ConstraintModels.Constraint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Constraints");
                });

            modelBuilder.Entity("Infrastructure.Models.ConstraintModels.ConstraintValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ConstraintId");

                    b.Property<string>("Value")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("ConstraintId");

                    b.ToTable("ConstraintValues");
                });

            modelBuilder.Entity("Infrastructure.Models.CustomObjectModels.FieldType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("Infrastructure.Models.IntermediateModels.TypeConstraint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ConstraintId");

                    b.Property<int>("TypeId");

                    b.HasKey("Id");

                    b.HasIndex("ConstraintId");

                    b.HasIndex("TypeId");

                    b.ToTable("Types_Support_Constraints");
                });

            modelBuilder.Entity("Infrastructure.Models.ConstraintModels.ConstraintValue", b =>
                {
                    b.HasOne("Infrastructure.Models.ConstraintModels.Constraint", "Constraint")
                        .WithMany()
                        .HasForeignKey("ConstraintId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Infrastructure.Models.IntermediateModels.TypeConstraint", b =>
                {
                    b.HasOne("Infrastructure.Models.ConstraintModels.Constraint")
                        .WithMany("SupportedTypes")
                        .HasForeignKey("ConstraintId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Infrastructure.Models.CustomObjectModels.FieldType", "FieldType")
                        .WithMany("SupportedConstraints")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
